trigger:
  - main
  - develop
  - feature/*
  - fix/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  env:
    NEXT_TELEMETRY_DISABLED: 1
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    contents: |
      .next/**
      package.json
      public/**
      manifest.yml
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'Container'