version: '3.1'

services:

  postgres-db:
    image: postgres:12.4
    restart: always
    volumes:
    - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: testing
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
    - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost
      PGADMIN_DEFAULT_PASSWORD: testing
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
    - "3080:80"

volumes:
  db:
    driver: local