# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
# - main


pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_12_x:
      node_version: 12.x
#    node_13_x:
#      node_version: 13.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js version : $(node_version)'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

#- task: CopyFiles@2
#  inputs:
#    SourceFolder: '$(System.DefaultWorkingDirectory)'
#    Contents: |
#      **\*.js
#      **\*.css
#      **\*.jpeg
#      **\*.png
#      package.json
#    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.ts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'